'use client';
import { useState } from 'react';
import { Copy, Check, Zap, RefreshCw } from 'lucide-react';
import { TRIBUNAL_API_BASE } from '@/lib/api';

const CARD = 'bg-white/60 backdrop-blur-md rounded-[28px] p-6 shadow-sm';

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  function copy() {
    navigator.clipboard.writeText(text).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); });
  }
  return (
    <button onClick={copy} className="flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-slate-200 bg-white text-xs font-medium text-slate-600 hover:border-slate-300 transition-colors">
      {copied ? <Check size={12} className="text-emerald-500" /> : <Copy size={12} />}
      {copied ? 'Copied' : 'Copy'}
    </button>
  );
}

const ENDPOINTS = [
  { platform: 'GitHub', event: 'pull_request (opened / synchronize)', path: '/webhook/github', color: 'bg-slate-900' },
  { platform: 'GitLab', event: 'Merge Request events', path: '/webhook/gitlab', color: 'bg-orange-600' },
  { platform: 'Bitbucket', event: 'pullrequest:created / pullrequest:updated', path: '/webhook/bitbucket', color: 'bg-blue-600' },
];

export default function WebhooksTab({ apiKey }: { apiKey: string }) {
  const [result, setResult] = useState<string | null>(null);
  const [testing, setTesting] = useState(false);

  async function runTest() {
    setTesting(true); setResult(null);
    try {
      const r = await fetch(`${TRIBUNAL_API_BASE}/analyze`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          repository: 'rohanpatel2002/tribunal', prNumber: 9999,
          files: [{
            path: 'payment_handler.go', status: 'modified',
            patch: '+// Generated by AI copilot\n+func RetryPayment() error {\n+  // retry against payment API\n+  return nil\n+}',
          }],
        }),
      });
      const d = await r.json();
      if (r.ok) setResult(`✅ Success — Recommendation: ${d.recommendation} | Files: ${d.totalFiles} | AI-generated: ${d.aiGenerated} | Critical: ${d.critical} | High: ${d.high}`);
      else setResult(`⚠️ Error ${r.status}: ${d.error ?? r.statusText}`);
    } catch (e: unknown) {
      setResult(`❌ Connection failed — is the Go server running? (${e instanceof Error ? e.message : e})`);
    }
    setTesting(false);
  }

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-[38px] font-light tracking-tight text-slate-900">Webhooks</h1>
        <p className="text-sm text-slate-500 mt-1">Configure your VCS to send PR events to TRIBUNAL</p>
      </div>

      {/* Endpoint cards */}
      <div className="space-y-4">
        {ENDPOINTS.map(({ platform, event, path, color }) => {
          const url = `${TRIBUNAL_API_BASE}${path}`;
          return (
            <div key={platform} className={CARD}>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div className={`w-8 h-8 rounded-lg ${color} flex items-center justify-center text-white text-[11px] font-bold`}>
                    {platform[0]}
                  </div>
                  <div>
                    <p className="font-semibold text-slate-800 text-sm">{platform}</p>
                    <p className="text-[11px] text-slate-500">Event: <code className="font-mono bg-slate-100 px-1 rounded">{event}</code></p>
                  </div>
                </div>
                <CopyButton text={url} />
              </div>
              <code className="text-xs font-mono text-slate-600 bg-slate-50 px-4 py-2.5 rounded-xl block border border-slate-100 truncate">
                POST {url}
              </code>
            </div>
          );
        })}
      </div>

      {/* Custom payload format */}
      <div className={CARD}>
        <h2 className="font-semibold text-slate-800 mb-2">Required Payload Format</h2>
        <p className="text-xs text-slate-500 mb-3">Each webhook must include a <code className="font-mono bg-slate-100 px-1 rounded">tribunal_files</code> array:</p>
        <pre className="bg-slate-950 text-emerald-400 text-[11px] font-mono p-4 rounded-2xl overflow-x-auto">
{`{
  "repository": { "full_name": "owner/repo" },
  "pull_request": { "number": 42 },
  "tribunal_files": [
    {
      "path": "src/handler.go",
      "status": "modified",
      "patch": "@@ ... +added lines"
    }
  ]
}`}
        </pre>
      </div>

      {/* Test analyzer */}
      <div className={CARD}>
        <h2 className="font-semibold text-slate-800 mb-1">Test Analyzer</h2>
        <p className="text-sm text-slate-500 mb-4">Sends a sample AI-generated payment retry patch to verify the pipeline end-to-end.</p>
        <button onClick={runTest} disabled={testing}
          className="flex items-center gap-2 px-6 py-2.5 bg-[#292b2a] text-white rounded-full text-sm font-medium hover:bg-black transition-colors disabled:opacity-60">
          {testing ? <RefreshCw size={14} className="animate-spin" /> : <Zap size={14} />}
          {testing ? 'Running…' : 'Run Test Analysis'}
        </button>
        {result && (
          <div className="mt-4 p-4 rounded-2xl bg-slate-50 border border-slate-100 text-sm text-slate-700 font-mono leading-relaxed">
            {result}
          </div>
        )}
      </div>
    </div>
  );
}
