package main

import (
	"bytes"
	"fmt"
	"time"
)

// GenerateContextBriefing takes an AnalyzeResponse and produces a robust markdown string
// matching the TRIBUNAL Context Briefing System standards.
func GenerateContextBriefing(resp *AnalyzeResponse) string {
	var buf bytes.Buffer

	// Title
	buf.WriteString(fmt.Sprintf("# Context Briefing: PR #%d\n\n", resp.PRNumber))

	// Executive Summary
	buf.WriteString("## Executive Summary\n")

	// Determine risk emoji
	riskEmoji := "✅"
	if resp.Summary.Recommendation == "BLOCK" {
		riskEmoji = "🚨"
	} else if resp.Summary.Recommendation == "REVIEW_REQUIRED" {
		riskEmoji = "⚠️"
	}

	buf.WriteString(fmt.Sprintf("%s **OVERALL STATUS: %s**\n", riskEmoji, resp.Summary.Recommendation))
	buf.WriteString(fmt.Sprintf("- Files Analyzed: %d\n", resp.Summary.TotalFiles))
	buf.WriteString(fmt.Sprintf("- AI-Generated Files: %d\n", resp.Summary.AIGenerated))

	buf.WriteString("- Risk Distribution:\n")
	buf.WriteString(fmt.Sprintf("  - Critical: %d\n", resp.Summary.Critical))
	buf.WriteString(fmt.Sprintf("  - High: %d\n", resp.Summary.High))
	buf.WriteString(fmt.Sprintf("  - Medium: %d\n", resp.Summary.Medium))
	buf.WriteString(fmt.Sprintf("  - Low: %d\n\n", resp.Summary.Low))

	// Detailed Findings
	if resp.Summary.Critical > 0 || resp.Summary.High > 0 {
		buf.WriteString("## Actionable Findings\n\n")
		for _, f := range resp.Results {
			if f.RiskLevel == "CRITICAL" || f.RiskLevel == "HIGH" || f.RiskLevel == "MEDIUM" {
				buf.WriteString(fmt.Sprintf("### %s\n", f.Path))

				emoji := "⚠️"
				if f.RiskLevel == "CRITICAL" {
					emoji = "🚨"
				}

				buf.WriteString(fmt.Sprintf("**Risk Level**: %s %s\n", f.RiskLevel, emoji))
				buf.WriteString(fmt.Sprintf("**AI Likelihood**: %.0f%%\n", f.AIScore*100))
				buf.WriteString(fmt.Sprintf("**Confidence**: %.0f%%\n", f.Confidence*100))
				buf.WriteString(fmt.Sprintf("\n**Summary**:\n%s\n\n", f.Summary))

				// Breakdown
				buf.WriteString("**Signal Breakdown**:\n")
				buf.WriteString(fmt.Sprintf("- Style mismatch: %.2f\n", f.Signals.Style))
				buf.WriteString(fmt.Sprintf("- Pattern anomaly: %.2f\n", f.Signals.Pattern))
				buf.WriteString(fmt.Sprintf("- Risk indicators: %.2f\n\n", f.Signals.Risk))
				buf.WriteString("---\n\n")
			}
		}
	} else {
		buf.WriteString("## Actionable Findings\n\nNo high-risk or critical changes detected. Standard review procedures apply.\n\n")
	}

	// Recommendation block
	buf.WriteString("## Recommendation\n\n")
	if resp.Summary.Recommendation == "APPROVE" {
		buf.WriteString("✋ **Low risk**. The changes align with established patterns and do not trigger AI or risk flags. Safe to proceed.\n\n")
	} else if resp.Summary.Recommendation == "REVIEW_REQUIRED" {
		buf.WriteString("✋ **REQUEST CHANGES / REVIEW**\n\nMultiple files exhibit anomalous patterns or AI-generation markers. Review the highlighted sections for business logic blindspots or contextual omissions.\n\n")
	} else {
		buf.WriteString("🛑 **BLOCK MERGE**\n\nCritical risk files identified. These changes exhibit very high likelihood of completely ignoring core system context (e.g., idempotency, scale, or security constraints). Please rewrite or provide heavy contextual justification.\n\n")
	}

	// Footer
	buf.WriteString("---\n\n")
	buf.WriteString("**Generated by TRIBUNAL**\n")
	buf.WriteString(fmt.Sprintf("`Analyzed: %s`\n", time.Now().UTC().Format("2006-01-02 15:04:05 UTC")))

	return buf.String()
}
