package main

import (
	"context"
	"testing"
	"time"
)

// TestContextFetcherGitHubIntegration tests GitHub context fetching
func TestContextFetcherGitHubIntegration(t *testing.T) {
	fetcher := NewContextFetcher("test-token")
	if fetcher == nil {
		t.Fatal("expected ContextFetcher to be created")
	}

	// Test parseRepoName
	owner, repo, err := parseRepoName("rohanpatel2002/tribunal")
	if err != nil {
		t.Fatalf("parseRepoName failed: %v", err)
	}

	if owner != "rohanpatel2002" {
		t.Errorf("expected owner 'rohanpatel2002', got %q", owner)
	}

	if repo != "tribunal" {
		t.Errorf("expected repo 'tribunal', got %q", repo)
	}
}

// TestParseDeploymentHistory tests parsing releases into deployment events
func TestParseDeploymentHistory(t *testing.T) {
	releases := []map[string]interface{}{
		{
			"tag_name":   "v1.0.0",
			"created_at": "2026-04-01T10:00:00Z",
			"body":       "Release 1.0.0 - 10 files changed",
		},
		{
			"tag_name":   "v1.0.1",
			"created_at": "2026-04-02T10:00:00Z",
			"body":       "Hotfix: critical incident resolved. 2 files changed.",
		},
	}

	history := parseDeploymentHistory(releases)

	if len(history) != 2 {
		t.Errorf("expected 2 deployment events, got %d", len(history))
	}

	if history[0].Version != "v1.0.0" {
		t.Errorf("expected first version to be v1.0.0, got %q", history[0].Version)
	}

	if history[1].Status != "partial_rollback" {
		t.Errorf("expected second deployment to be marked as partial_rollback, got %q", history[1].Status)
	}
}

// TestExtractIncidentPatterns tests incident extraction from releases
func TestExtractIncidentPatterns(t *testing.T) {
	releases := []map[string]interface{}{
		{
			"tag_name":   "v1.0.1",
			"created_at": "2026-04-02T10:00:00Z",
			"body":       "CRITICAL INCIDENT: Database migration caused data loss. Rolled back immediately.",
		},
	}

	patterns := extractIncidentPatterns(releases)

	if len(patterns) != 1 {
		t.Errorf("expected 1 incident pattern, got %d", len(patterns))
	}

	if patterns[0].Severity != "CRITICAL" {
		t.Errorf("expected CRITICAL severity, got %q", patterns[0].Severity)
	}
}

// TestEnhancedBriefingGeneration tests briefing synthesis
func TestEnhancedBriefingGeneration(t *testing.T) {
	gen := NewEnhancedBriefingGenerator()
	if gen == nil {
		t.Fatal("expected BriefingGenerator to be created")
	}

	resp := &AnalyzeResponse{
		Repository:     "rohanpatel2002/tribunal",
		PRNumber:       42,
		Recommendation: "REVIEW_REQUIRED",
		TotalFiles:     5,
		AIGenerated:    2,
		Critical:       0,
		High:           1,
		Medium:         1,
		Low:            3,
		Files: []FileAnalysis{
			{
				Path:          "db/migration.go",
				AIScore:       0.85,
				IsAIGenerated: true,
				RiskLevel:     "HIGH",
				Summary:       "AI-generated database migration without idempotency checks",
				Signals: SignalBreakdown{
					Style:   0.8,
					Pattern: 0.9,
					Risk:    0.7,
				},
			},
		},
	}

	ctx := &RepositoryContext{
		ContextRelevanceScore: 0.8,
		ServiceDependencies: []ServiceDep{
			{ServiceName: "app", Dependency: "postgres", Type: "db", Critical: true},
		},
		Incidents: []IncidentPattern{
			{
				Title:       "Migration Deadlock",
				Severity:    "HIGH",
				Description: "Database migration locked tables",
				RootCause:   "Missing lock timeout",
			},
		},
	}

	briefing := gen.GenerateEnhancedBriefing(resp, ctx)

	if briefing == "" {
		t.Fatal("expected non-empty briefing")
	}

	// Verify briefing contains expected content
	if len(briefing) < 100 {
		t.Errorf("briefing seems too short: %d chars", len(briefing))
	}

	// Verify key sections
	requiredSections := []string{
		"TRIBUNAL Context Briefing",
		"Executive Summary",
		"PR #42",
		"REVIEW_REQUIRED",
	}

	for _, section := range requiredSections {
		if !contains(briefing, section) {
			t.Errorf("briefing missing required section: %q", section)
		}
	}
}

// TestBuildResponseWithContext tests end-to-end analysis with context
func TestBuildResponseWithContext(t *testing.T) {
	req := AnalyzeRequest{
		Repository: "rohanpatel2002/tribunal",
		PRNumber:   42,
		Files: []ChangedFile{
			{
				Path:   "detector.go",
				Status: "modified",
				Patch:  "generated by ai, here is the code",
			},
		},
	}

	// Test with nil LLM (should use heuristics)
	resp := BuildResponse(context.Background(), req, nil, "")

	if resp.Repository != "rohanpatel2002/tribunal" {
		t.Errorf("expected repository rohanpatel2002/tribunal, got %q", resp.Repository)
	}

	if resp.PRNumber != 42 {
		t.Errorf("expected PR number 42, got %d", resp.PRNumber)
	}

	if len(resp.Files) == 0 {
		t.Fatal("expected at least 1 file analysis")
	}

	// Briefing generation (should work even without context)
	gen := NewEnhancedBriefingGenerator()
	briefing := gen.GenerateEnhancedBriefing(&resp, nil)

	if briefing == "" {
		t.Fatal("expected non-empty briefing even without context")
	}
}

// TestContextRelevanceScoring tests how context relevance is calculated
func TestContextRelevanceScoring(t *testing.T) {
	ctx := &RepositoryContext{
		ReadmeContent:     "# My Project",
		RunbookSummary:    "How to run the project",
		ArchitectureNotes: "System architecture",
		DeploymentHistory: []DeploymentEvent{
			{Version: "v1.0.0", Date: time.Now().Format(time.RFC3339)},
		},
	}

	score := calculateContextScore(ctx)

	if score < 0.7 || score > 1.0 {
		t.Errorf("expected context relevance score between 0.7 and 1.0, got %.2f", score)
	}
}

// Helper: contains checks if string contains substring
func contains(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}

// BenchmarkEnhancedBriefingGeneration benchmarks briefing synthesis
func BenchmarkEnhancedBriefingGeneration(b *testing.B) {
	gen := NewEnhancedBriefingGenerator()

	resp := &AnalyzeResponse{
		Repository:     "rohanpatel2002/tribunal",
		PRNumber:       42,
		Recommendation: "REVIEW_REQUIRED",
		TotalFiles:     20,
		AIGenerated:    5,
		Critical:       2,
		High:           5,
		Medium:         8,
		Low:            5,
	}

	ctx := &RepositoryContext{
		ContextRelevanceScore: 0.8,
		Incidents: []IncidentPattern{
			{Title: "Incident 1", Severity: "HIGH"},
			{Title: "Incident 2", Severity: "MEDIUM"},
		},
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = gen.GenerateEnhancedBriefing(resp, ctx)
	}
}
