package main

import "testing"

func TestAnalyzeFile_Deterministic(t *testing.T) {
	file := ChangedFile{
		Path:   "db/migration.sql",
		Status: "modified",
		Patch:  "ALTER TABLE users ADD COLUMN active_status TEXT; -- generated by AI with robust strategy",
	}

	first := AnalyzeFile(file)
	second := AnalyzeFile(file)

	if first.AIScore != second.AIScore || first.RiskLevel != second.RiskLevel || first.Confidence != second.Confidence {
		t.Fatalf("expected deterministic analysis, got first=%+v second=%+v", first, second)
	}
}

func TestAnalyzeFile_HighRiskKeywords(t *testing.T) {
	file := ChangedFile{
		Path:  "payments/retry.go",
		Patch: "retry payment transaction without idempotent key and feature flag rollout",
	}

	result := AnalyzeFile(file)
	if result.RiskLevel != "HIGH" && result.RiskLevel != "CRITICAL" {
		t.Fatalf("expected HIGH or CRITICAL risk, got %s", result.RiskLevel)
	}
}

func TestBuildRecommendation(t *testing.T) {
	critical := buildRecommendation(AnalysisSummary{Critical: 1})
	if critical != "BLOCK" {
		t.Fatalf("expected BLOCK, got %s", critical)
	}

	review := buildRecommendation(AnalysisSummary{AIGenerated: 2})
	if review != "REVIEW_REQUIRED" {
		t.Fatalf("expected REVIEW_REQUIRED, got %s", review)
	}

	approve := buildRecommendation(AnalysisSummary{Low: 2})
	if approve != "APPROVE" {
		t.Fatalf("expected APPROVE, got %s", approve)
	}
}

func TestValidateAnalyzeRequest(t *testing.T) {
	err := validateAnalyzeRequest(AnalyzeRequest{})
	if err == nil {
		t.Fatal("expected validation error for empty request")
	}

	okReq := AnalyzeRequest{
		Repository: "rohanpatel2002/tribunal",
		PRNumber:   7,
		Files: []ChangedFile{{
			Path:   "main.go",
			Status: "modified",
			Patch:  "fmt.Println(\"hello\")",
		}},
	}

	err = validateAnalyzeRequest(okReq)
	if err != nil {
		t.Fatalf("expected valid request, got error: %v", err)
	}
}
