package main

import (
	"context"
	"fmt"
	"log/slog"
	"math"
	"regexp"
	"strings"
	"sync"
)

const (
	aiThreshold          = 0.65
	maxPatchLength       = 12000
	maxSummaryPatchChars = 220
)

var (
	verboseIdentifierRegex = regexp.MustCompile(`[a-zA-Z]{20,}`)
	aiMarkerRegex          = regexp.MustCompile(`(?i)(generated by|as an ai|certainly|here('| i)?s|let me|comprehensive|robust|best practice)`)
	explicitAIMarkerRegex  = regexp.MustCompile(`(?i)(generated\s+by\s+ai|copilot|chatgpt|claude|llm|ai[- ]generated|as\s+an\s+ai)`)
	riskKeywordRegex       = regexp.MustCompile(`(?i)(alter table|migration|retry|idempotent|feature flag|payment|transaction|lock|downtime|backfill)`)
	criticalRiskRegex      = regexp.MustCompile(`(?i)(drop table|truncate|delete from|lock table|payment|transaction|non-idempotent|downtime)`)
)

// AnalyzeFile evaluates a single changed file using either dynamic God-Mode context LLM or deterministic heuristics.
func AnalyzeFile(ctx context.Context, file ChangedFile, llm LLMIntegrator, repoContext string) FileAnalysis {
	// If we have an LLM configured, try that first for accurate AI risk scoring
	if llm != nil {
		llmRes, err := llm.AnalyzeCode(ctx, file.Path, file.Patch, repoContext)
		if err == nil && llmRes != nil {
			return FileAnalysis{
				Path:          file.Path,
				AIScore:       llmRes.AIScore,
				IsAIGenerated: llmRes.IsAIGenerated,
				Confidence:    llmRes.Confidence,
				RiskLevel:     llmRes.RiskLevel,
				Summary:       llmRes.Summary,
				SuggestedFix:  llmRes.SuggestedFix,
				Signals: SignalBreakdown{
					Style:   0,
					Pattern: 0,
					Risk:    0,
				},
			}
		}
		// Fallback to heuristic scoring if LLM fails
		if err != nil {
			slog.Warn("LLM analysis failed, falling back to heuristic engine", "file", file.Path, "error", err)
		}
	}

	patch := truncate(file.Patch, maxPatchLength)
	styleScore := scoreStyleSignal(patch)
	patternScore := scorePatternSignal(patch)
	riskScore := scoreRiskSignal(patch)

	aiScore := calculateAIScore(patch, styleScore, patternScore, riskScore)
	riskLevel := classifyRisk(riskScore)
	confidence := round(confidenceFromScore(aiScore, aiThreshold), 2)

	return FileAnalysis{
		Path:          file.Path,
		AIScore:       aiScore,
		IsAIGenerated: aiScore >= aiThreshold,
		Confidence:    confidence,
		Signals: SignalBreakdown{
			Style:   styleScore,
			Pattern: patternScore,
			Risk:    riskScore,
		},
		RiskLevel: riskLevel,
		Summary:   buildFileSummary(file.Path, aiScore, riskLevel, patch),
	}
}

func scoreStyleSignal(patch string) float64 {
	if strings.TrimSpace(patch) == "" {
		return 0.05
	}

	lines := strings.Split(patch, "\n")
	totalLines := float64(len(lines))
	if totalLines == 0 {
		return 0.05
	}

	longIdentifiers := float64(len(verboseIdentifierRegex.FindAllString(patch, -1)))
	commentLines := 0.0
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "/*") {
			commentLines++
		}
	}

	verbosity := math.Min(1.0, longIdentifiers/(totalLines*0.15+1))
	commentBalance := 1.0 - math.Min(1.0, commentLines/(totalLines*0.4+1))
	return round((verbosity*0.6)+(commentBalance*0.4), 2)
}

func scorePatternSignal(patch string) float64 {
	if strings.TrimSpace(patch) == "" {
		return 0.05
	}

	if hasExplicitAIMarker(patch) {
		// High-confidence marker from prompt leakage or explicit attribution.
		return 0.95
	}

	matches := len(aiMarkerRegex.FindAllString(patch, -1))
	if matches == 0 {
		return 0.15
	}

	score := 0.15 + (float64(matches) * 0.18)
	if score > 1.0 {
		score = 1.0
	}
	return round(score, 2)
}

func scoreRiskSignal(patch string) float64 {
	if strings.TrimSpace(patch) == "" {
		return 0.1
	}

	normalized := strings.ToLower(patch)
	riskMatches := len(riskKeywordRegex.FindAllString(normalized, -1))
	criticalMatches := len(criticalRiskRegex.FindAllString(normalized, -1))

	if riskMatches == 0 && criticalMatches == 0 {
		return 0.2
	}

	score := 0.2 + (float64(riskMatches) * 0.16)

	if criticalMatches > 0 {
		score += 0.30 * float64(criticalMatches)
	}

	if strings.Contains(normalized, "retry") && strings.Contains(normalized, "idempotent") {
		score += 0.18
	}

	if score > 1.0 {
		score = 1.0
	}
	return round(score, 2)
}

func calculateAIScore(patch string, styleScore, patternScore, riskScore float64) float64 {
	// AI authorship should be driven primarily by stylistic/pattern evidence.
	base := (styleScore * 0.35) + (patternScore * 0.50) + (riskScore * 0.15)

	if hasExplicitAIMarker(patch) {
		base += 0.20
	}

	if base > 1.0 {
		base = 1.0
	}

	return round(base, 2)
}

func hasExplicitAIMarker(patch string) bool {
	return explicitAIMarkerRegex.MatchString(patch)
}

func classifyRisk(riskScore float64) string {
	switch {
	case riskScore >= 0.85:
		return "CRITICAL"
	case riskScore >= 0.65:
		return "HIGH"
	case riskScore >= 0.45:
		return "MEDIUM"
	default:
		return "LOW"
	}
}

// BuildResponse constructs the final JSON payload containing file-by-file God-Mode analysis.
func BuildResponse(ctx context.Context, req AnalyzeRequest, llm LLMIntegrator, repoContext string) AnalyzeResponse {
	results := make([]FileAnalysis, len(req.Files))
	summary := AnalysisSummary{TotalFiles: len(req.Files)}

	var wg sync.WaitGroup
	for i, file := range req.Files {
		wg.Add(1)
		go func(index int, f ChangedFile) {
			defer wg.Done()
			results[index] = AnalyzeFile(ctx, f, llm, repoContext)
		}(i, file)
	}
	wg.Wait()

	for _, res := range results {
		if res.IsAIGenerated {
			summary.AIGenerated++
		}

		switch res.RiskLevel {
		case "CRITICAL":
			summary.Critical++
		case "HIGH":
			summary.High++
		case "MEDIUM":
			summary.Medium++
		default:
			summary.Low++
		}
	}

	summary.Recommendation = buildRecommendation(summary)

	return AnalyzeResponse{
		Repository: req.Repository,
		PRNumber:   req.PRNumber,
		Summary:    summary,
		Results:    results,
	}
}

func buildRecommendation(summary AnalysisSummary) string {
	if summary.Critical > 0 {
		return "BLOCK"
	}
	if summary.High > 0 || summary.AIGenerated > 0 {
		return "REVIEW_REQUIRED"
	}
	return "APPROVE"
}

func buildFileSummary(path string, aiScore float64, riskLevel string, patch string) string {
	trimmed := strings.TrimSpace(strings.ReplaceAll(patch, "\n", " "))
	preview := truncate(trimmed, maxSummaryPatchChars)
	if preview == "" {
		preview = "empty or binary patch"
	}

	return fmt.Sprintf("%s: aiScore=%.2f risk=%s preview=%q", path, aiScore, riskLevel, preview)
}

func truncate(s string, max int) string {
	if max <= 0 || len(s) <= max {
		return s
	}
	return s[:max]
}

func round(value float64, places int) float64 {
	factor := math.Pow(10, float64(places))
	return math.Round(value*factor) / factor
}

func confidenceFromScore(score, threshold float64) float64 {
	distance := math.Abs(score - threshold)
	if threshold <= 0 || threshold >= 1 {
		return round(math.Min(1.0, distance), 2)
	}
	maxDistance := math.Max(threshold, 1-threshold)
	if maxDistance == 0 {
		return 1.0
	}
	return math.Min(1.0, distance/maxDistance)
}
