package main

import (
	"strings"
	"testing"
)

func TestAnalyzeFile_Deterministic(t *testing.T) {
	file := ChangedFile{
		Path:   "db/migration.sql",
		Status: "modified",
		Patch:  "ALTER TABLE users ADD COLUMN active_status TEXT; -- generated by AI with robust strategy",
	}

	first := AnalyzeFile(file)
	second := AnalyzeFile(file)

	if first.AIScore != second.AIScore || first.RiskLevel != second.RiskLevel || first.Confidence != second.Confidence {
		t.Fatalf("expected deterministic analysis, got first=%+v second=%+v", first, second)
	}
}

func TestAnalyzeFile_HighRiskKeywords(t *testing.T) {
	file := ChangedFile{
		Path:  "payments/retry.go",
		Patch: "retry payment transaction without idempotent key and feature flag rollout",
	}

	result := AnalyzeFile(file)
	if result.RiskLevel != "HIGH" && result.RiskLevel != "CRITICAL" {
		t.Fatalf("expected HIGH or CRITICAL risk, got %s", result.RiskLevel)
	}
}

func TestBuildRecommendation(t *testing.T) {
	critical := buildRecommendation(AnalysisSummary{Critical: 1})
	if critical != "BLOCK" {
		t.Fatalf("expected BLOCK, got %s", critical)
	}

	review := buildRecommendation(AnalysisSummary{AIGenerated: 2})
	if review != "REVIEW_REQUIRED" {
		t.Fatalf("expected REVIEW_REQUIRED, got %s", review)
	}

	approve := buildRecommendation(AnalysisSummary{Low: 2})
	if approve != "APPROVE" {
		t.Fatalf("expected APPROVE, got %s", approve)
	}
}

func TestAnalyzeFile_EmptyPatchDefaults(t *testing.T) {
	result := AnalyzeFile(ChangedFile{Path: "empty.txt", Patch: ""})

	if result.RiskLevel != "LOW" {
		t.Fatalf("expected LOW risk for empty patch, got %s", result.RiskLevel)
	}
	if result.AIScore < 0 || result.AIScore > 1 {
		t.Fatalf("aiScore out of bounds: %f", result.AIScore)
	}
}

func TestAnalyzeFile_TruncatesLongPatchInSummary(t *testing.T) {
	longPatch := strings.Repeat("a", maxSummaryPatchChars+100)
	result := AnalyzeFile(ChangedFile{Path: "long.txt", Patch: longPatch})

	if len(result.Summary) == 0 {
		t.Fatal("expected non-empty summary")
	}
	if strings.Contains(result.Summary, strings.Repeat("a", maxSummaryPatchChars+50)) {
		t.Fatal("summary appears to include untruncated patch content")
	}
}

func TestAnalyzeFile_ExplicitAIMarkerDetected(t *testing.T) {
	file := ChangedFile{
		Path:  "ai.py",
		Patch: "# generated by AI using Claude\ndef process_data():\n    pass",
	}

	result := AnalyzeFile(file)
	if !result.IsAIGenerated {
		t.Fatalf("expected explicit AI marker to be flagged, got score %.2f", result.AIScore)
	}
}

func TestHasExplicitAIMarker(t *testing.T) {
	if !hasExplicitAIMarker("-- generated by AI") {
		t.Fatal("expected explicit AI marker to match")
	}
	if hasExplicitAIMarker("normal handwritten change") {
		t.Fatal("did not expect explicit AI marker for normal text")
	}
}

func TestAnalyzeFile_RetryIdempotentEscalation(t *testing.T) {
	file := ChangedFile{
		Path:  "payments/retry.py",
		Patch: "retry payment transaction without idempotent key on timeout",
	}

	result := AnalyzeFile(file)
	if result.Signals.Risk < 0.85 {
		t.Fatalf("expected elevated risk score for retry/idempotent combo, got %.2f", result.Signals.Risk)
	}
	if result.RiskLevel != "CRITICAL" && result.RiskLevel != "HIGH" {
		t.Fatalf("expected HIGH/CRITICAL risk, got %s", result.RiskLevel)
	}
}

func TestAnalyzeFile_DropTableEscalation(t *testing.T) {
	file := ChangedFile{
		Path:  "schema/drop.sql",
		Patch: "DROP TABLE users;",
	}

	result := AnalyzeFile(file)
	if result.Signals.Risk < 0.3 {
		t.Fatalf("expected elevated risk for DROP TABLE, got %.2f", result.Signals.Risk)
	}
	if result.RiskLevel == "LOW" {
		t.Fatalf("expected non-LOW risk level for DROP TABLE, got %s", result.RiskLevel)
	}
}

func TestBuildRecommendation_Matrix(t *testing.T) {
	tests := []struct {
		name  string
		input AnalysisSummary
		want  string
	}{
		{name: "critical takes precedence", input: AnalysisSummary{Critical: 1, High: 3}, want: "BLOCK"},
		{name: "high requires review", input: AnalysisSummary{High: 1}, want: "REVIEW_REQUIRED"},
		{name: "ai generated requires review", input: AnalysisSummary{AIGenerated: 1}, want: "REVIEW_REQUIRED"},
		{name: "low only approve", input: AnalysisSummary{Low: 2}, want: "APPROVE"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := buildRecommendation(tc.input)
			if got != tc.want {
				t.Fatalf("expected %s, got %s", tc.want, got)
			}
		})
	}
}

func TestValidateAnalyzeRequest(t *testing.T) {
	err := validateAnalyzeRequest(AnalyzeRequest{})
	if err == nil {
		t.Fatal("expected validation error for empty request")
	}

	okReq := AnalyzeRequest{
		Repository: "rohanpatel2002/tribunal",
		PRNumber:   7,
		Files: []ChangedFile{{
			Path:   "main.go",
			Status: "modified",
			Patch:  "fmt.Println(\"hello\")",
		}},
	}

	err = validateAnalyzeRequest(okReq)
	if err != nil {
		t.Fatalf("expected valid request, got error: %v", err)
	}
}
