package main

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestAnalyzeHandler_MethodNotAllowed(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/analyze", nil)
	rr := httptest.NewRecorder()

	analyzeHandler(rr, req)

	if rr.Code != http.StatusMethodNotAllowed {
		t.Fatalf("expected %d, got %d", http.StatusMethodNotAllowed, rr.Code)
	}
}

func TestAnalyzeHandler_InvalidJSON(t *testing.T) {
	req := httptest.NewRequest(http.MethodPost, "/analyze", strings.NewReader("{"))
	rr := httptest.NewRecorder()

	analyzeHandler(rr, req)

	if rr.Code != http.StatusBadRequest {
		t.Fatalf("expected %d, got %d", http.StatusBadRequest, rr.Code)
	}
}

func TestAnalyzeHandler_ValidRequest(t *testing.T) {
	body := `{"repository":"rohanpatel2002/tribunal","prNumber":12,"files":[{"path":"main.go","status":"modified","patch":"// generated by AI"}]}`
	req := httptest.NewRequest(http.MethodPost, "/analyze", strings.NewReader(body))
	rr := httptest.NewRecorder()

	analyzeHandler(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected %d, got %d body=%s", http.StatusOK, rr.Code, rr.Body.String())
	}
}

func TestValidateAnalyzeRequest_StatusValidation(t *testing.T) {
	err := validateAnalyzeRequest(AnalyzeRequest{
		Repository: "rohanpatel2002/tribunal",
		PRNumber:   1,
		Files: []ChangedFile{{
			Path:   "a.go",
			Status: "unknown",
			Patch:  "x",
		}},
	})

	if err == nil {
		t.Fatal("expected status validation error")
	}
}

func TestValidateAnalyzeRequest_MissingStatus(t *testing.T) {
	err := validateAnalyzeRequest(AnalyzeRequest{
		Repository: "rohanpatel2002/tribunal",
		PRNumber:   1,
		Files: []ChangedFile{{
			Path:   "a.go",
			Status: "",
			Patch:  "x",
		}},
	})

	if err == nil {
		t.Fatal("expected missing status validation error")
	}
}

func TestGithubWebhookHandler_ValidPayload(t *testing.T) {
	body := `{"action":"opened","repository":{"full_name":"rohanpatel2002/tribunal"},"pull_request":{"number":8},"tribunal_files":[{"path":"main.go","status":"modified","patch":"retry payment transaction"}]}`
	req := httptest.NewRequest(http.MethodPost, "/webhook/github", strings.NewReader(body))
	rr := httptest.NewRecorder()

	githubWebhookHandler(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected %d, got %d body=%s", http.StatusOK, rr.Code, rr.Body.String())
	}
}
