package main

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
)

// MockGitHubClient is a mock implementation of the GitHubIntegrator for testing.
type MockGitHubClient struct {
	CreateCheckRunFunc         func(ctx context.Context, repository string, headSHA string, name string) (int64, error)
	UpdateCheckRunFunc         func(ctx context.Context, repository string, checkRunID int64, opts UpdateCheckRunOptions) error
	FetchRepositoryContextFunc func(ctx context.Context, repository string, headSHA string) (string, error)
}

func (m *MockGitHubClient) CreateCheckRun(ctx context.Context, repository string, headSHA string, name string) (int64, error) {
	if m.CreateCheckRunFunc != nil {
		return m.CreateCheckRunFunc(ctx, repository, headSHA, name)
	}
	return 12345, nil
}

func (m *MockGitHubClient) UpdateCheckRun(ctx context.Context, repository string, checkRunID int64, opts UpdateCheckRunOptions) error {
	if m.UpdateCheckRunFunc != nil {
		return m.UpdateCheckRunFunc(ctx, repository, checkRunID, opts)
	}
	return nil
}

func (m *MockGitHubClient) FetchRepositoryContext(ctx context.Context, repository string, headSHA string) (string, error) {
	if m.FetchRepositoryContextFunc != nil {
		return m.FetchRepositoryContextFunc(ctx, repository, headSHA)
	}
	return "# Mock Repo Context\nThis is a test repository context configuration.", nil
}

func TestAnalyzeHandler_MethodNotAllowed(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/analyze", nil)
	rr := httptest.NewRecorder()

	h := NewHandler(nil, &MockGitHubClient{}, nil, nil)
	h.analyzeHandler(rr, req)

	if rr.Code != http.StatusMethodNotAllowed {
		t.Fatalf("expected %d, got %d", http.StatusMethodNotAllowed, rr.Code)
	}
}

func TestAnalyzeHandler_InvalidJSON(t *testing.T) {
	req := httptest.NewRequest(http.MethodPost, "/analyze", strings.NewReader("{"))
	rr := httptest.NewRecorder()

	h := NewHandler(nil, &MockGitHubClient{}, nil, nil)
	h.analyzeHandler(rr, req)

	if rr.Code != http.StatusBadRequest {
		t.Fatalf("expected %d, got %d", http.StatusBadRequest, rr.Code)
	}
}

func TestAnalyzeHandler_ValidRequest(t *testing.T) {
	payload := `{"repository":"rohanpatel2002/tribunal","prNumber":12,"files":[{"path":"main.go","status":"modified","patch":"// generated by AI"}]}`
	req := httptest.NewRequest(http.MethodPost, "/analyze", strings.NewReader(payload))
	rr := httptest.NewRecorder()

	h := NewHandler(nil, &MockGitHubClient{}, nil, nil)
	h.analyzeHandler(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected %d, got %d body=%s", http.StatusOK, rr.Code, rr.Body.String())
	}
}

func TestValidateAnalyzeRequest_StatusValidation(t *testing.T) {
	err := validateAnalyzeRequest(AnalyzeRequest{
		Repository: "rohanpatel2002/tribunal",
		PRNumber:   1,
		Files: []ChangedFile{{
			Path:   "a.go",
			Status: "unknown",
			Patch:  "x",
		}},
	})

	if err == nil {
		t.Fatal("expected status validation error")
	}
}

func TestValidateAnalyzeRequest_MissingStatus(t *testing.T) {
	err := validateAnalyzeRequest(AnalyzeRequest{
		Repository: "rohanpatel2002/tribunal",
		PRNumber:   1,
		Files: []ChangedFile{{
			Path:   "a.go",
			Status: "",
			Patch:  "x",
		}},
	})

	if err == nil {
		t.Fatal("expected missing status validation error")
	}
}

func TestGithubWebhookHandler_ValidPayload(t *testing.T) {
	payload := `{"action":"opened","repository":{"full_name":"rohanpatel2002/tribunal"},"pull_request":{"number":8,"head":{"sha":"abc123def"}},"tribunal_files":[{"path":"main.go","status":"modified","patch":"retry payment transaction"}]}`
	req := httptest.NewRequest(http.MethodPost, "/webhook/github", strings.NewReader(payload))
	req.Header.Set("X-GitHub-Delivery", "test-delivery-id-12345")
	rr := httptest.NewRecorder()

	h := NewHandler(nil, &MockGitHubClient{}, nil, nil)
	h.githubWebhookHandler(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected %d, got %d", http.StatusOK, rr.Code)
	}
}

func TestGithubWebhookHandler_AlreadyProcessed(t *testing.T) {
	mockRepo := &MockRepository{
		processed: map[string]bool{"duplicate-delivery-id-999": true},
	}
	h := NewHandler(mockRepo, nil, nil, nil)
	payload := `{"action":"opened","repository":{"full_name":"rohanpatel2002/tribunal"},"pull_request":{"number":9,"head":{"sha":"abc123def"}},"tribunal_files":[{"path":"main.go","status":"modified","patch":"test"}]}`
	req := httptest.NewRequest(http.MethodPost, "/webhook/github", strings.NewReader(payload))
	req.Header.Set("X-GitHub-Delivery", "duplicate-delivery-id-999")

	rr := httptest.NewRecorder()
	h.githubWebhookHandler(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected %d, got %d", http.StatusOK, rr.Code)
	}
	if !strings.Contains(rr.Body.String(), "webhook already processed") {
		t.Fatalf("expected idempotency message, got %s", rr.Body.String())
	}
}

// MockRepository helps simulate database interactions for HTTP testing without a real Postgres instance
type MockRepository struct {
	SaveFunc                 func(ctx context.Context, response *AnalyzeResponse) error
	GetFunc                  func(ctx context.Context, repository string, prNumber int) (*AnalyzeResponse, error)
	MarkWebhookProcessedFunc func(ctx context.Context, deliveryID string, repoFullName string) (bool, error)
	GetAuditSummaryFunc      func(ctx context.Context, repository string) (*AuditSummary, error)
	processed                map[string]bool
}

func (m *MockRepository) SaveAnalysis(ctx context.Context, response *AnalyzeResponse) error {
	if m.SaveFunc != nil {
		return m.SaveFunc(ctx, response)
	}
	return nil
}

func (m *MockRepository) GetRecentAnalyses(ctx context.Context, limit int, repository string) ([]PRAnalysisRecord, error) {
	return nil, nil // Return empty list for successful tests requiring no data by default
}
func (m *MockRepository) GetAnalysisByPR(ctx context.Context, repository string, prNumber int) (*AnalyzeResponse, error) {
	if m.GetFunc != nil {
		return m.GetFunc(ctx, repository, prNumber)
	}
	return nil, ErrAnalysisNotFound
}

func (m *MockRepository) MarkWebhookProcessed(ctx context.Context, deliveryID string, repoFullName string) (bool, error) {
	if m.processed[deliveryID] {
		return false, nil
	}
	m.processed[deliveryID] = true
	return true, nil
}

func (m *MockRepository) GetRepositoryAuditSummary(ctx context.Context, repository string) (*AuditSummary, error) {
	return &AuditSummary{
		Repository: repository,
	}, nil
}

func (m *MockRepository) GetSubscriptionTier(ctx context.Context, repoFullName string) (string, error) {
	return "FREE", nil
}

func (m *MockRepository) SaveSecurityPolicy(ctx context.Context, policy *SecurityPolicy) error {
	return nil
}

func (m *MockRepository) GetSecurityPolicies(ctx context.Context, repository string) ([]SecurityPolicy, error) {
	return []SecurityPolicy{}, nil
}

func (m *MockRepository) DeleteSecurityPolicy(ctx context.Context, repository string, policyName string, actor string) error {
	return nil
}

func TestGetAnalysisHandler_Success(t *testing.T) {
	mockRepo := &MockRepository{
		GetFunc: func(ctx context.Context, repo string, pr int) (*AnalyzeResponse, error) {
			return &AnalyzeResponse{
				Repository:     repo,
				PRNumber:       pr,
				Recommendation: "APPROVE",
			}, nil
		},
	}

	h := NewHandler(mockRepo, &MockGitHubClient{}, nil, nil)
	req := httptest.NewRequest(http.MethodGet, "/analysis?repo=rohanpatel2002/tribunal&pr=100", nil)
	rr := httptest.NewRecorder()

	h.getAnalysisHandler(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected %d, got %d", http.StatusOK, rr.Code)
	}
	if !strings.Contains(rr.Body.String(), "APPROVE") {
		t.Fatalf("expected body to contain APPROVE, got: %s", rr.Body.String())
	}
}

func TestGitHubConnectStartHandler_NotConfigured(t *testing.T) {
	t.Setenv("GITHUB_OAUTH_CLIENT_ID", "")

	h := NewHandler(nil, nil, nil, nil)
	req := httptest.NewRequest(http.MethodGet, "/api/v1/github/connect/start", nil)
	rr := httptest.NewRecorder()

	h.githubConnectStartHandler(rr, req)

	if rr.Code != http.StatusServiceUnavailable {
		t.Fatalf("expected %d, got %d", http.StatusServiceUnavailable, rr.Code)
	}
}

func TestGitHubConnectionStatusHandler_NoSession(t *testing.T) {
	_ = os.Unsetenv("GITHUB_OAUTH_CLIENT_ID")

	h := NewHandler(nil, nil, nil, nil)
	req := httptest.NewRequest(http.MethodGet, "/api/v1/github/connect/status", nil)
	rr := httptest.NewRecorder()

	h.githubConnectionStatusHandler(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected %d, got %d", http.StatusOK, rr.Code)
	}

	if !strings.Contains(rr.Body.String(), "\"connected\":false") {
		t.Fatalf("expected disconnected status, got body=%s", rr.Body.String())
	}
}

func TestGetAnalysisHandler_NotFound(t *testing.T) {
	mockRepo := &MockRepository{
		GetFunc: func(ctx context.Context, repo string, pr int) (*AnalyzeResponse, error) {
			return nil, ErrAnalysisNotFound
		},
	}

	h := NewHandler(mockRepo, &MockGitHubClient{}, nil, nil)
	req := httptest.NewRequest(http.MethodGet, "/analysis?repo=rohanpatel2002/tribunal&pr=999", nil)
	rr := httptest.NewRecorder()

	h.getAnalysisHandler(rr, req)

	if rr.Code != http.StatusNotFound {
		t.Fatalf("expected %d, got %d", http.StatusNotFound, rr.Code)
	}
}

func TestGetAnalysisHandler_NoDBConfigured(t *testing.T) {
	// Notice we pass nil for the repository
	h := NewHandler(nil, &MockGitHubClient{}, nil, nil)
	req := httptest.NewRequest(http.MethodGet, "/analysis?repo=rohanpatel2002/tribunal&pr=100", nil)
	rr := httptest.NewRecorder()

	h.getAnalysisHandler(rr, req)

	if rr.Code != http.StatusServiceUnavailable {
		t.Fatalf("expected Service Unavailable %d, got %d", http.StatusServiceUnavailable, rr.Code)
	}
}
